name: Build RPM

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: create tarball
        shell: bash
        run: |
          version="$(grep Version jobinfo.spec | awk '{print $2}')"
          mkdir SOURCES
          mkdir SPECS
          cp jobinfo.spec SPECS
          mkdir jobinfo-${version}
          cp jobinfo pynumparser.py jobinfo-${version}
          tar -czf SOURCES/jobinfo-${version}.tar.gz jobinfo-${version}

      - name: rpmbuild
        uses: ./.github/actions/rpmbuild/
        #uses: robertdebock/rpmbuild-action@1.0.0
